/*
 * MySQL
 * Schema for database `previous_year_questions` or `rdsbca$previous_year_questions`.
 * Created by: Suraj Kumar Giri
 * Created on: 8th Jan 2023
 * Last updated on: 10th Jan 2023
 */
----
-- 1. Table `brabu` 
----
CREATE TABLE IF NOT EXISTS `brabu`(
    `SNo` SMALLINT UNSIGNED NOT NULL UNIQUE AUTO_INCREMENT,
    `Year` SMALLINT UNSIGNED PRIMARY KEY NOT NULL,
    `Sem1` MEDIUMINT UNSIGNED UNIQUE,
    `Sem2` MEDIUMINT UNSIGNED UNIQUE,
    `Sem3` MEDIUMINT UNSIGNED UNIQUE,
    `Sem4` MEDIUMINT UNSIGNED UNIQUE,
    `Sem5` MEDIUMINT UNSIGNED UNIQUE
);

----
-- 2. Table `ln_mishra` 
----
CREATE TABLE IF NOT EXISTS `ln_mishra`(
    `SNo` SMALLINT UNSIGNED NOT NULL UNIQUE AUTO_INCREMENT,
    `Year` SMALLINT UNSIGNED PRIMARY KEY NOT NULL,
    `Sem1` MEDIUMINT UNSIGNED UNIQUE,
    `Sem2` MEDIUMINT UNSIGNED UNIQUE,
    `Sem3` MEDIUMINT UNSIGNED UNIQUE,
    `Sem4` MEDIUMINT UNSIGNED UNIQUE,
    `Sem5` MEDIUMINT UNSIGNED UNIQUE
);

----
-- 3. Table `vaishali` 
----
CREATE TABLE IF NOT EXISTS `vaishali`(
    `SNo` SMALLINT UNSIGNED NOT NULL UNIQUE AUTO_INCREMENT,
    `Year` SMALLINT UNSIGNED PRIMARY KEY NOT NULL,
    `Sem1` MEDIUMINT UNSIGNED UNIQUE,
    `Sem2` MEDIUMINT UNSIGNED UNIQUE,
    `Sem3` MEDIUMINT UNSIGNED UNIQUE,
    `Sem4` MEDIUMINT UNSIGNED UNIQUE,
    `Sem5` MEDIUMINT UNSIGNED UNIQUE
);